version: '3'

services:
  app:
    container_name: front
    build: .
    ports:
      - '3000:3000'
    working_dir: '/src'
    volumes:
      - './:/src'
      - node_modules_volume:/node_modules
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
volumes:
  node_modules_volume:
